FROM nginx

RUN mkdir openssl && cd openssl
# THIS IS A CA - Not sure how this might work?
# RUN openssl req -x509 \
#             -sha256 -days 365 \
#             -nodes \
#             -newkey rsa:2048 \
#             -subj "/CN=demo.mlopshub.com/C=US/L=San Fransisco" \
#             -keyout rootCA.key -out rootCA.crt 
RUN openssl req -new -x509 -days 365 -nodes \
  -keyout nginx-selfsigned.key\ 
  -out nginx-selfsigned.crt\
  -subj "/O=OpenBenches/CN=localhost"

#RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt